CREATE TABLE E8 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description VARCHAR(255));	

CREATE TABLE E6 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description VARCHAR(255));

CREATE TABLE E18 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description VARCHAR(255));

CREATE TABLE E3 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description VARCHAR(255));

CREATE TABLE E4 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description VARCHAR(255));

CREATE TABLE E2 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description VARCHAR(255));

CREATE TABLE E19 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description VARCHAR(255));

CREATE TABLE E34 (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description VARCHAR(255));

INSERT INTO errors (num_error)
VALUES (8);

INSERT INTO errors (num_error)
VALUES (18);

INSERT INTO errors (num_error)
VALUES (34);

INSERT INTO errors (num_error)
VALUES (37);

SELECT * FROM errors;

DROP TABLE errors;